### ISSUE TITLE
Explicitly mention name of environment variable for token

### ISSUE THREAD

**Issue by hypebright** [devOpifex/shinymetrics#12]
When getting the token it is clearly stated that you should use the token in an .Renviron file:

<img width="1065" alt="image" src="https://github.com/devOpifex/shinymetrics/assets/60436372/e836b56c-ee3a-4916-9728-43edf593b691">

However, it does not mention what the name should be. For clarity I would add `SHINYMETRICS_TOKEN=[your_token]`

You can also think about updating the code example, because if the environment variable is set you don't have to specify the `token=` argument.

**Comment by JohnCoene** [comment]
This was indeed not clear. It's now in the documentation.

Thank you!
