### ISSUE TITLE
Possibly wrong numbers in User Devices chart

### ISSUE THREAD

**Issue by DivadNojnarg** [devOpifex/shinymetrics#14]
Given that more than 5000 events are recorded, it seems unlikely that only 1 event is on PC and the other is on mobile (this isn't consistent with other charts).

<img width="1792" alt="Screenshot 2023-08-11 at 18 25 46" src="https://github.com/devOpifex/shinymetrics/assets/18291543/6c8d41b3-1cb7-487f-910a-96af273c800f">

**Comment by JohnCoene** [comment]
Thanks for sharing this!

Caught COVID so I can't check now but I will as soon as I'm well again.

**Comment by JohnCoene** [comment]
Fix will be online soon, thanks for reporting this!
