### ISSUE TITLE
shinyapps.io getting error when trying to install shinymetrics

### ISSUE THREAD

**Issue by simitpatel** [devOpifex/shinymetrics#17]
I'm trying to deploy an app to shinyapps.io that uses shinymetrics. I'm getting the following error:

```Error building image: Error fetching shinymetrics (0.0.1.9000) source. Error accessing GitHub repository devOpifex/shinymetrics. HTTP 401: Unauthorized```

I have my shinyapps.io account connected to GitHub and able to use my github token for package downloading (though this is a public package so that should not be necessary?).

thoughts on how to get around this?

**Comment by simitpatel** [comment]
nevermind! i got it working :) in case this happens to anyone else, just unauth and then re-auth your github account on shinyapps.io. i did that and then it worked :)

**Comment by JohnCoene** [comment]
Ah phew, thank you, glad to hear this worked!
