### ISSUE TITLE
Don't manage to see historical logs even after 1h collection

### ISSUE THREAD

**Issue by DivadNojnarg** [devOpifex/shinymetrics#3]
I can see real-time data but contrary to what the UI says "Data collected in the past hour, data over an hour old is available under "historical" tabs.", I don't see anything when I visit > 2h later.

**Comment by DivadNojnarg** [comment]
It actually takes a bit more time (~3-4h) but I can finally see it.

**Comment by JohnCoene** [comment]
Sorry, I should have replied earlier.

A bug somewhere, I know what it is, did not fix yet but a restart did the job for now :)

Thanks again for reporting this!

**Comment by JohnCoene** [comment]
Thanks for this, it's still an issue.
Closing and moving to main repo.
