### ISSUE TITLE
tracking dashboard: rename "errors" to "reliability" in sidebar menu

### ISSUE THREAD

**Issue by DivadNojnarg** [devOpifex/shinymetrics#5]
When I click on errors, I would expect to only see errors. In that case, I would rename it "reliability" so I can see either errors or "correct" sessions. 

<img width="1236" alt="Screenshot 2023-07-14 at 15 44 30" src="https://github.com/devOpifex/shinymetrics/assets/18291543/e5f2bb47-ecdd-4bbf-8441-614c8dcb9104">

**Comment by JohnCoene** [comment]
Agree
