### ISSUE TITLE
tracking dashboard: app url overlap with dashboard body and projects cards

### ISSUE THREAD

**Issue by DivadNojnarg** [devOpifex/shinymetrics#6]
<img width="1236" alt="Screenshot 2023-07-14 at 15 44 30" src="https://github.com/devOpifex/shinymetrics/assets/18291543/7c2ba594-a0f5-4ca4-bbae-550d049bdd93">
<img width="599" alt="Screenshot 2023-07-14 at 15 49 19" src="https://github.com/devOpifex/shinymetrics/assets/18291543/9b9cac25-53dd-4834-836a-7cfb1d199a8e">

**Comment by JohnCoene** [comment]
Thank you for this!

**Comment by DivadNojnarg** [comment]
Is there a new version deployed?

**Comment by JohnCoene** [comment]
Redeploying new version now, service might be down for 2 mins
